### ISSUE TITLE
Learn Jupyter Book

### ISSUE THREAD

**Issue by ErikStrijbos** [CentreForDigitalHumanities/Summer-School-2024#6]
## Jupyter
- [ ] [Overview](https://jupyterbook.org/en/stable/start/overview.html)
  - [ ] [Introduction](https://jupyterbook.org/en/stable/intro.html)

## Instead of Quarto
- [ ] Install [Quarto](https://quarto.org/docs/get-started/)
- [ ] Include in [VS Code](https://quarto.org/docs/get-started/hello/vscode.html) / [Jupyter ](https://quarto.org/docs/get-started/hello/jupyter.html)/ [RStudio](https://quarto.org/docs/get-started/hello/rstudio.html)
- [ ] ...

[Guide](https://quarto.org/docs/guide/)

**Comment by 73616e646572** [comment]
Decided to go for with Jupyter Notebooks for now.
